In [21]:
#1.NUMPY BOLUMU
#numpy ile matris islemleri
import numpy as np
matris = np.random.randint(0, 101, size=(5, 5))
print("matris:", matris)
print("ortalama:", np.mean(matris))
print("standart sapma:", np.std(matris))
print("varyans:", np.var(matris))
print("en buyuk deger:", np.max(matris))
print("en kucuk deger:", np.min(matris))
print("kosegenlerdeki elemanlarin toplami:", np.trace(matris))

#numpy ile veri simulasyonu
puanlar = np.random.normal(loc=50, scale=15, size=1000)
puanlar = np.array([min(max(p, 0), 100) for p in puanlar])
print("ortalama:", np.mean(puanlar))
print("medyan:", np.median(puanlar))
print("standart sapma:", np.std(puanlar))
print("50'den dusuk ogrenci sayisi:", np.sum(puanlar < 50))

matris: [[ 0 77 99 55  3]
 [85  6 99 38 25]
 [60 87 72 40 32]
 [10  4 20 85 47]
 [37  2  4 17 19]]
ortalama: 40.92
standart sapma: 32.863256077266605
varyans: 1079.9936000000002
en buyuk deger: 99
en kucuk deger: 0
kosegenlerdeki elemanlarin toplami: 182
ortalama: 49.78273437097406
medyan: 49.56826426864284
standart sapma: 15.010091682635409
50'den dusuk ogrenci sayisi: 511


In [20]:
#PANDAS BOLUMU
import pandas as pd
#1. veri setini pandas dataframe olarak olusturdum
data = { "ogrenci": ["ali", "ayse", "mehmet", "zeynep", "ahmet"],
    "yas": [20, 21, 19, 22, 20],
    "bolum": ["bilgisayar", "fizik", "kimya", "bilgisayar", "fizik"],
    "sinav1": [70, 65, 80, 60, 75],
    "sinav2": [85, 80, 70, 65, 90],
    "sinav3": [55, 60, 70, 80, 85]  }
df = pd.DataFrame(data)
print(df)

#2. her ders icin ortalama puani buldum
ortalama = df[["sinav1", "sinav2", "sinav3"]].mean()
print("ortalamalar:\n", ortalama)

#3. en yuksek mat notunu alan ogrenci
en_yuksek_not = df["sinav1"].max()
ogrenci = df[df["sinav1"] == en_yuksek_not]["ogrenci"].values[0]
print(f"en yuksek matematik notu alan ogrenci: {ogrenci}")

#4. tum ogrencilerin not ort
df = pd.DataFrame(data)
df["ortalama"] = df[["sinav1", "sinav2", "sinav3"]].mean(axis=1)
print(df)

#5. her bolumun ortalamasi
df = pd.DataFrame(data)
bolum_ort = df.groupby("bolum")[["sinav1", "sinav2", "sinav3"]].mean()
print(bolum_ort)

#6. ort 70 uzeri olan ogrenciler
df["ortalama"] = df[["sinav1", "sinav2", "sinav3"]].mean(axis=1)
ort_70_uzeri = df[df["ortalama"] > 70]
print(ort_70_uzeri)

  ogrenci  yas       bolum  sinav1  sinav2  sinav3
0     ali   20  bilgisayar      70      85      55
1    ayse   21       fizik      65      80      60
2  mehmet   19       kimya      80      70      70
3  zeynep   22  bilgisayar      60      65      80
4   ahmet   20       fizik      75      90      85
ortalamalar:
 sinav1    70.0
sinav2    78.0
sinav3    70.0
dtype: float64
en yuksek matematik notu alan ogrenci: mehmet
  ogrenci  yas       bolum  sinav1  sinav2  sinav3   ortalama
0     ali   20  bilgisayar      70      85      55  70.000000
1    ayse   21       fizik      65      80      60  68.333333
2  mehmet   19       kimya      80      70      70  73.333333
3  zeynep   22  bilgisayar      60      65      80  68.333333
4   ahmet   20       fizik      75      90      85  83.333333
            sinav1  sinav2  sinav3
bolum                             
bilgisayar    65.0    75.0    67.5
fizik         70.0    85.0    72.5
kimya         80.0    70.0    70.0
  ogrenci  yas  bolum  sina